# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1378735440);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1344514490);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1350045454);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1411880290);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1344514610);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 215040);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 348160);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140924083558");
user_pref("browser.slowStartup.averageTime", 641);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "http://ser.cs.fit.edu/ser2014/");
user_pref("browser.startup.homepage_override.buildID", "20140924083558");
user_pref("browser.startup.homepage_override.mstone", "32.0.3");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1378821719853");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1411880231524");
user_pref("datareporting.policy.firstRunTime", "1378735319852");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 584);
user_pref("datareporting.sessions.current.main", 20);
user_pref("datareporting.sessions.current.sessionRestored", 657);
user_pref("datareporting.sessions.current.startTime", "1412035665145");
user_pref("datareporting.sessions.current.totalTime", 21);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.2", "{\"s\":1411880169131,\"a\":12,\"t\":156,\"c\":true,\"m\":10,\"fp\":274,\"sr\":1418}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1411881497356,\"a\":1,\"t\":2,\"c\":true,\"m\":11,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1412035485540,\"a\":7,\"t\":35,\"c\":true,\"m\":51,\"fp\":659,\"sr\":724}");
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.9,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:32.0.3");
user_pref("extensions.getAddons.cache.lastUpdate", 1411880170);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1408486745000,\"rdfTime\":1401829706000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1411549861000,\"rdfTime\":1411549861000}}}]");
user_pref("extensions.lastAppVersion", "32.0.3");
user_pref("extensions.lastPlatformVersion", "32.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/plugin");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20140924083558");
user_pref("gecko.mstone", "32.0.3");
user_pref("idle.lastDailyNotification", 1411880254);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1411880254);
user_pref("places.history.expiration.transient_current_max_pages", 7781);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1411880254);
user_pref("toolkit.startup.last_success", 1412035665);
user_pref("toolkit.telemetry.previousBuildID", "20140924083558");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1346254637);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
